# Generated by Django 3.0 on 2020-12-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vo', models.IntegerField(verbose_name='Vacas en ordeno')),
                ('vpp', models.IntegerField(verbose_name='Vacas Pre Parto')),
                ('vs', models.IntegerField(verbose_name='Vacas Secas')),
                ('vaq', models.IntegerField(verbose_name='Vaquillonas en servicio')),
                ('vaq_crecimiento', models.IntegerField(verbose_name='Vaquillonas en desarrollo')),
                ('toros', models.IntegerField(verbose_name='Toros')),
                ('terneros', models.IntegerField(verbose_name='Terneros en guachera')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'ordering': ['fecha'],
            },
        ),
    ]
