# Generated by Django 3.0 on 2020-12-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existencia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Existencia', 'verbose_name_plural': 'Existencias'},
        ),
    ]
