# Generated by Django 3.0 on 2020-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_auto_20201228_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencia',
            name='vaq',
        ),
        migrations.AddField(
            model_name='existencia',
            name='vaq_pc',
            field=models.IntegerField(default=0, verbose_name='Vaquillonas prenadas'),
            preserve_default=False,
        ),
    ]
