# Generated by Django 3.0 on 2021-01-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_auto_20201229_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
