# Generated by Django 3.0 on 2021-01-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_existencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProLeche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lts_venta', models.IntegerField(verbose_name='Litros vendidos')),
                ('lts_terneros', models.IntegerField(verbose_name='Litros Terneros')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.Existencia', verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Produccion de leche',
                'verbose_name_plural': 'Producciones de leche',
                'ordering': ['-fecha'],
            },
        ),
    ]
