# Generated by Django 3.0 on 2021-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_proleche_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosProductivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vo', models.IntegerField(verbose_name='Vacas en ordeno')),
                ('vpp', models.IntegerField(verbose_name='Vacas Pre Parto')),
                ('vs', models.IntegerField(verbose_name='Vacas Secas')),
                ('vaq_pc', models.IntegerField(verbose_name='Vaquillonas prenadas')),
                ('vaq_crecimiento', models.IntegerField(verbose_name='Vaquillonas en desarrollo')),
                ('toros', models.IntegerField(verbose_name='Toros')),
                ('terneros', models.IntegerField(verbose_name='Terneros en guachera')),
                ('lts_venta', models.IntegerField(verbose_name='Litros vendidos')),
                ('lts_terneros', models.IntegerField(verbose_name='Litros Terneros')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Datos productivos',
                'verbose_name_plural': 'Datos productivos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='proleche',
            name='fecha',
        ),
        migrations.DeleteModel(
            name='Existencia',
        ),
        migrations.DeleteModel(
            name='ProLeche',
        ),
    ]
