# Generated by Django 3.0 on 2021-01-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_auto_20210104_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosproductivos',
            name='lts_terneros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Litros Terneros'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='lts_venta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Litros vendidos'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='terneros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Terneros en guachera'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='toros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Toros'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vaq_crecimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vaquillonas en desarrollo'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vaq_pc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vaquillonas prenadas'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vacas en ordeno'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vpp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vacas Pre Parto'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vacas Secas'),
        ),
    ]
