# Generated by Django 3.0 on 2021-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_auto_20210104_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosproductivos',
            name='lts_terneros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lts.cons'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='lts_venta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lts.vta'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='terneros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Terneros'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vaq_crecimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vaq.Crec'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vaq_pc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vaq.P'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vo',
            field=models.IntegerField(blank=True, null=True, verbose_name='VO'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vpp',
            field=models.IntegerField(blank=True, null=True, verbose_name='VPP'),
        ),
        migrations.AlterField(
            model_name='datosproductivos',
            name='vs',
            field=models.IntegerField(blank=True, null=True, verbose_name='VS'),
        ),
    ]
