# Generated by Django 3.0 on 2021-01-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_auto_20210104_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosproductivos',
            old_name='lts_terneros',
            new_name='lts_consumo',
        ),
        migrations.RenameField(
            model_name='datosproductivos',
            old_name='vaq_crecimiento',
            new_name='vaq_crec',
        ),
        migrations.RenameField(
            model_name='datosproductivos',
            old_name='vaq_pc',
            new_name='vaq_p',
        ),
    ]
