# Generated by Django 3.0 on 2021-01-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_auto_20210104_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngesoAlimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cereales', 'Cereales'), ('ConcTamb', 'Concentrado tambo'), ('ConcTern', 'Concentrado terneros'), ('ConcRecr', 'Concentrado recria'), ('Rollos', 'Rollos'), ('Silo', 'Silo')], max_length=50, verbose_name='Tipo de alimento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre alimento')),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unit', models.IntegerField(verbose_name='Precio unitario')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.DatosProductivos')),
            ],
        ),
    ]
