# Generated by Django 3.0 on 2021-01-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_ingesoalimentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngesoAlimentos',
            new_name='IngresoAlimentos',
        ),
    ]
